/*
 * Copyright (2021) The Delta Lake Project Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.delta.tables

import org.apache.spark.annotation._
import org.apache.spark.sql.types.{DataType, StructField}

/**
 * :: Evolving ::
 *
 * Builder to specify a table column.
 *
 * See [[DeltaTableBuilder]] for examples.
 * @since 1.0.0
 */
@Evolving
abstract class DeltaColumnBuilder {

  /**
   * :: Evolving ::
   *
   * Specify the column data type.
   *
   * @param dataType string column data type
   * @return this DeltaColumnBuilder
   * @since 1.0.0
   */
  @Evolving
  def dataType(dataType: String): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify the column data type.
   *
   * @param dataType DataType column data type
   * @return this DeltaColumnBuilder
   * @since 1.0.0
   */
  @Evolving
  def dataType(dataType: DataType): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify whether the column can be null.
   *
   * @param nullable boolean whether the column can be null or not.
   * @return this DeltaColumnBuilder
   * @since 1.0.0
   */
  @Evolving
  def nullable(nullable: Boolean): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify an expression if the column is always generated as a function of other columns.
   *
   * @param expr string the generation expression
   * @return this DeltaColumnBuilder
   * @since 1.0.0
   */
  @Evolving
  def generatedAlwaysAs(expr: String): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify a column as an identity column with default values that is always generated
   * by the system (i.e. does not allow user-specified values).
   *
   * @return this DeltaColumnBuilder
   * @since 3.3.0
   */
  @Evolving
  def generatedAlwaysAsIdentity(): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify a column as an identity column that is always generated by the system (i.e. does not
   * allow user-specified values).
   *
   * @param start the start value of the identity column
   * @param step the increment step of the identity column
   * @return this DeltaColumnBuilder
   * @since 3.3.0
   */
  @Evolving
  def generatedAlwaysAsIdentity(start: Long, step: Long): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify a column as an identity column that allows user-specified values such that the
   * generated values use default start and step values.
   *
   * @return this DeltaColumnBuilder
   * @since 3.3.0
   */
  @Evolving
  def generatedByDefaultAsIdentity(): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify a column as an identity column that allows user-specified values.
   *
   * @param start the start value of the identity column
   * @param step the increment step of the identity column
   * @return this DeltaColumnBuilder
   * @since 3.3.0
   */
  @Evolving
  def generatedByDefaultAsIdentity(start: Long, step: Long): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Specify a column comment.
   *
   * @param comment string column description
   * @return this DeltaColumnBuilder
   * @since 1.0.0
   */
  @Evolving
  def comment(comment: String): DeltaColumnBuilder

  /**
   * :: Evolving ::
   *
   * Build the column as a StructField.
   *
   * @return StructField representing the column
   * @since 1.0.0
   */
  @Evolving
  def build(): StructField
}
